name: Server Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login --username celidur --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build ./server/ --file ./server/Dockerfile --tag ghcr.io/celidur/polynoel-server-ghcr:lastest
        docker push ghcr.io/celidur/polynoel-server-ghcr:lastest
